services:

  Markocupic\RssFeedGeneratorBundle\Feed\FeedItem: ~

  Markocupic\RssFeedGeneratorBundle\Formatter\Formatter:
    arguments:
      - '%markocupic_rss_feed_generator.filter%'

  Markocupic\RssFeedGeneratorBundle\Feed\FeedFactory:
    arguments:
      - '@Markocupic\RssFeedGeneratorBundle\Formatter\Formatter'






